/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegopokemon;

import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Francis
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSALIR = new javax.swing.JButton();
        btnRESET = new javax.swing.JButton();
        JPanek = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEcurar = new javax.swing.JButton();
        btnEfiraga = new javax.swing.JButton();
        btnErampage = new javax.swing.JButton();
        btnEsuper = new javax.swing.JButton();
        vida1 = new javax.swing.JProgressBar();
        vida2 = new javax.swing.JProgressBar();
        vida3 = new javax.swing.JProgressBar();
        vida4 = new javax.swing.JProgressBar();
        btnRcurar = new javax.swing.JButton();
        btnRthundaga = new javax.swing.JButton();
        btnRdark = new javax.swing.JButton();
        btnRsuper = new javax.swing.JButton();
        btnAcurar = new javax.swing.JButton();
        btnAice = new javax.swing.JButton();
        btnAfrenzy = new javax.swing.JButton();
        btnAsuper = new javax.swing.JButton();
        lblActions = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSALIR.setText("Salir");
        btnSALIR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSALIRMousePressed(evt);
            }
        });

        btnRESET.setText("Reset");
        btnRESET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRESETMousePressed(evt);
            }
        });

        JPanek.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/ed2.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/dr1.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/ag2.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sprites/enem1.png"))); // NOI18N

        btnEcurar.setText("Curaga");
        btnEcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEcurarMousePressed(evt);
            }
        });

        btnEfiraga.setText("Firaga");
        btnEfiraga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEfiragaMousePressed(evt);
            }
        });

        btnErampage.setText("Rampage");
        btnErampage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnErampageMousePressed(evt);
            }
        });

        btnEsuper.setText("SUPER");
        btnEsuper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEsuperMousePressed(evt);
            }
        });

        vida1.setValue(100);

        vida2.setValue(100);

        vida3.setToolTipText("");
        vida3.setValue(100);

        vida4.setValue(300);

        btnRcurar.setText("Curaga");
        btnRcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRcurarMousePressed(evt);
            }
        });

        btnRthundaga.setText("Thundaga");
        btnRthundaga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRthundagaMousePressed(evt);
            }
        });
        btnRthundaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRthundagaActionPerformed(evt);
            }
        });

        btnRdark.setText("Dark Nebula");
        btnRdark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRdarkMousePressed(evt);
            }
        });

        btnRsuper.setText("SUPER");
        btnRsuper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRsuperMousePressed(evt);
            }
        });

        btnAcurar.setText("Curaga");
        btnAcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAcurarMousePressed(evt);
            }
        });

        btnAice.setText("Ice");
        btnAice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAiceMousePressed(evt);
            }
        });

        btnAfrenzy.setText("Frenzy");
        btnAfrenzy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAfrenzyMousePressed(evt);
            }
        });

        btnAsuper.setText("SUPER");
        btnAsuper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAsuperMousePressed(evt);
            }
        });

        javax.swing.GroupLayout JPanekLayout = new javax.swing.GroupLayout(JPanek);
        JPanek.setLayout(JPanekLayout);
        JPanekLayout.setHorizontalGroup(
            JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanekLayout.createSequentialGroup()
                .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanekLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanekLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnErampage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEfiraga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEsuper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanekLayout.createSequentialGroup()
                        .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanekLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRcurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRsuper, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRdark, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnRthundaga, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAsuper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAfrenzy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAcurar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)))))
                .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanekLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanekLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanekLayout.createSequentialGroup()
                                .addComponent(vida4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanekLayout.createSequentialGroup()
                                .addComponent(lblActions, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))))))
        );
        JPanekLayout.setVerticalGroup(
            JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanekLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanekLayout.createSequentialGroup()
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanekLayout.createSequentialGroup()
                        .addComponent(btnEcurar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEfiraga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnErampage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEsuper, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRsuper, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAsuper, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPanekLayout.createSequentialGroup()
                            .addComponent(btnRcurar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRthundaga)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRdark)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addGroup(JPanekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanekLayout.createSequentialGroup()
                                .addComponent(vida4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblActions, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(JPanekLayout.createSequentialGroup()
                                .addComponent(btnAcurar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAfrenzy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Música");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSALIR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRESET)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JPanek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSALIR)
                    .addComponent(btnRESET)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JPanek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSALIRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSALIRMousePressed
        System.exit(0);
    }//GEN-LAST:event_btnSALIRMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        AudioClip song;
        song = java.applet.Applet.newAudioClip(getClass().getResource("/Musica/serpent.wav"));
        song.play();
    }//GEN-LAST:event_jButton1MousePressed

    private void btnRESETMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRESETMousePressed
        vida1.setValue(100);
        vida2.setValue(100);
        vida3.setValue(100);
        vida4.setValue(300);
        
                         btnEcurar.setEnabled(true);
                         btnAcurar.setEnabled(true);
                         btnRcurar.setEnabled(true);
                         btnEfiraga.setEnabled(true);
                         btnRthundaga.setEnabled(true);
                         btnAice.setEnabled(true);
                         btnErampage.setEnabled(true);
                         btnEsuper.setEnabled(true);
                         btnRdark.setEnabled(true);
                         btnRsuper.setEnabled(true);
                         btnAsuper.setEnabled(true);
                         btnAfrenzy.setEnabled(true);
                        
        lblActions.setText(" ");
        JOptionPane.showMessageDialog(null,"GAME HAS BEEN RESET.");
    }//GEN-LAST:event_btnRESETMousePressed

    private void btnRthundagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRthundagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRthundagaActionPerformed

    private void btnEcurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEcurarMousePressed
        double random = Math.random()*15;
        final int new1 = vida1.getValue()+(int)random;
        vida1.setValue(new1);
        final int new2 = vida2.getValue();
        final int new3 = vida3.getValue();
        
        if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
            JOptionPane.showMessageDialog(null, "Has Perdido!");
            btnEcurar.setEnabled(false);
            btnAcurar.setEnabled(false);
            btnRcurar.setEnabled(false);
            btnEfiraga.setEnabled(false);
            btnRthundaga.setEnabled(false);
            btnAice.setEnabled(false);
            btnErampage.setEnabled(false);
            btnEsuper.setEnabled(false);
            btnRdark.setEnabled(false);
            btnRsuper.setEnabled(false);
            btnAsuper.setEnabled(false);
            btnAfrenzy.setEnabled(false);
        } 
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = (int)Math.random()*15;
                    int new1 = vida1.getValue()-(int)random;
                    vida1.setValue(new1);
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
        
                        if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = (int)Math.random()*15;
                    int new4 = vida4.getValue()+(int)random;
                    vida4.setValue(new4);
                    if(new4<=0)
                    {
                        lblActions.setText("Has ganado!");
                    }
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida1.setValue(1);
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
        
                     if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado un super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        lblActions.setText("Has ganado!");
                    }
                }
        }
       });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnEcurarMousePressed

    private void btnEfiragaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEfiragaMousePressed
        double random = Math.random()*15;
        int nuevavida2 = vida4.getValue()-(int)random;
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida1.getValue()-(int)random;
                    vida1.setValue(new1);
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
        
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        lblActions.setText("Has ganado!");
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida1.setValue(1);
                    int new1 = vida1.getValue();
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        lblActions.setText("Has ganado!");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start(); 
    }//GEN-LAST:event_btnEfiragaMousePressed

    private void btnErampageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnErampageMousePressed
        double random = Math.random()*20;
        int nuevavida2 = vida4.getValue()-(int)random;
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida1.getValue()-(int)random;
                    vida1.setValue(new1);
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        lblActions.setText("Has ganado!");
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida1.setValue(1);
                    int new1 = vida1.getValue();
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        lblActions.setText("Has ganado!");
                        
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnErampageMousePressed

    private void btnEsuperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEsuperMousePressed
        double random = Math.random()*11;
        btnEsuper.setEnabled(false);
        int nuevavida2 = vida4.getValue()-(int)random;
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            lblActions.setText("Has ganado!");
            
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida1.getValue()-(int)random;
                    vida1.setValue(new1);
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        lblActions.setText("Has ganado!");
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida1.setValue(1);
                    int new1 = vida1.getValue();
                    final int new2 = vida2.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        lblActions.setText("Has ganado!");
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnEsuperMousePressed

    private void btnRcurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRcurarMousePressed
        double random = Math.random()*15;
        final int new1 = vida2.getValue()+(int)random;
        vida2.setValue(new1);
        
        final int new2 = vida1.getValue();
        final int new3 = vida3.getValue();
        if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
            JOptionPane.showMessageDialog(null, "Has Perdido!");
            btnEcurar.setEnabled(false);
            btnAcurar.setEnabled(false);
            btnRcurar.setEnabled(false);
            btnEfiraga.setEnabled(false);
            btnRthundaga.setEnabled(false);
            btnAice.setEnabled(false);
            btnErampage.setEnabled(false);
            btnEsuper.setEnabled(false);
            btnRdark.setEnabled(false);
            btnRsuper.setEnabled(false);
            btnAsuper.setEnabled(false);
            btnAfrenzy.setEnabled(false);
        } 
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = (int)Math.random()*15;
                    int new1 = vida2.getValue()-(int)random;
                    vida2.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        lblActions.setText("Has perdido!");
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = (int)Math.random()*15;
                    int new4 = vida4.getValue()+(int)random;
                    vida4.setValue(new4);
                    if(new4<=0)
                    {
                        lblActions.setText("Has ganado!");
                    }
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida2.setValue(1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                       
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado un super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        lblActions.setText("Has ganado!");
                    }
                }
        }
       });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnRcurarMousePressed

    private void btnRthundagaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRthundagaMousePressed
        double random = Math.random()*15;
        int new1 = vida4.getValue()-(int)random;
        vida4.setValue(new1);
        final int new2 = vida1.getValue();
        final int new3 = vida3.getValue();
        if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida2.getValue()-(int)random;
                    vida2.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida2.setValue(1);
                    int new1 = vida2.getValue();
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(100);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnRthundagaMousePressed

    private void btnRdarkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRdarkMousePressed
        double random = Math.random()*20;
        int nuevavida2 = vida4.getValue()-(int)random;
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida2.getValue()-(int)random;
                    vida2.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida2.setValue(1);
                    int new1 = vida2.getValue();
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                        
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnRdarkMousePressed

    private void btnRsuperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRsuperMousePressed
        double random = Math.random()*11;
        int nuevavida2 = vida4.getValue()-(int)random;
        btnRsuper.setEnabled(false);
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
            
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida2.getValue()-(int)random;
                    vida2.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida2.setValue(1);
                    int new1 = vida2.getValue();
                    final int new2 = vida1.getValue();
                    final int new3 = vida3.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnRsuperMousePressed

    private void btnAcurarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcurarMousePressed
        double random = Math.random()*15;
        final int new1 = vida3.getValue()+(int)random;
        vida3.setValue(new1);
        final int new2 = vida1.getValue();
        final int new3 = vida2.getValue();
        if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
            JOptionPane.showMessageDialog(null, "Has Perdido!");
            btnEcurar.setEnabled(false);
            btnAcurar.setEnabled(false);
            btnRcurar.setEnabled(false);
            btnEfiraga.setEnabled(false);
            btnRthundaga.setEnabled(false);
            btnAice.setEnabled(false);
            btnErampage.setEnabled(false);
            btnEsuper.setEnabled(false);
            btnRdark.setEnabled(false);
            btnRsuper.setEnabled(false);
            btnAsuper.setEnabled(false);
            btnAfrenzy.setEnabled(false);
        } 
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = (int)Math.random()*15;
                    int new1 = vida3.getValue()-(int)random;
                    vida3.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = (int)Math.random()*15;
                    int new4 = vida4.getValue()+(int)random;
                    vida4.setValue(new4);
                    if(new4<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida3.setValue(1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado un super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }
        }
       });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnAcurarMousePressed

    private void btnAiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAiceMousePressed
        double random = Math.random()*15;
        int nuevavida2 = vida4.getValue()-(int)random;
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida3.getValue()-(int)random;
                    vida3.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida3.setValue(1);
                    int new1 = vida3.getValue();
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(100);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnAiceMousePressed

    private void btnAfrenzyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAfrenzyMousePressed
        double random = Math.random()*20;
        int nuevavida2 = vida4.getValue()-(int)random;
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida3.getValue()-(int)random;
                    vida3.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida3.setValue(1);
                    int new1 = vida3.getValue();
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                        
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnAfrenzyMousePressed

    private void btnAsuperMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsuperMousePressed
        double random = Math.random()*11;
        int nuevavida2 = vida4.getValue()-(int)random;
        btnAsuper.setEnabled(false);
        vida4.setValue(nuevavida2);
        if(nuevavida2<=0)
        {
            JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
            
        }
        
        Timer timer = new Timer(1000, new AbstractAction(){
            @Override
            public void actionPerformed(ActionEvent ae){
                int ataque1 = (int)Math.random()*100;
                
                if(ataque1<40)
                {
                    lblActions.setText("Enemigo ha utilizado ataque normal!");
                    double random = Math.random()*15;
                    int new1 = vida3.getValue()-(int)random;
                    vida3.setValue(new1);
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else if(ataque1<80)
                {
                    lblActions.setText("Enemigo ha utilizado curaga!");
                    double random = Math.random()*15;
                    int nuevavidae = vida4.getValue()+(int)random;
                    vida4.setValue(nuevavidae);
                    if(nuevavidae <=0){
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                    
                }else if(ataque1<90)
                {
                    lblActions.setText("Enemigo ha utilizado un super ataque!");
                    vida3.setValue(1);
                    int new1 = vida3.getValue();
                    final int new2 = vida1.getValue();
                    final int new3 = vida2.getValue();
                    if((new1<=0 && new2 <=0) || (new1<=0 && new3<=0) || (new2<=0 && new3<=0)){
                        JOptionPane.showMessageDialog(null, "Has Perdido!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }else
                {
                    lblActions.setText("Enemigo ha utilizado super curaga!");
                    vida4.setValue(300);
                    int nuevavidae = vida4.getValue();
                    if(nuevavidae<=0)
                    {
                        JOptionPane.showMessageDialog(null, "Has Ganado!");
                         btnEcurar.setEnabled(false);
                         btnAcurar.setEnabled(false);
                         btnRcurar.setEnabled(false);
                         btnEfiraga.setEnabled(false);
                         btnRthundaga.setEnabled(false);
                         btnAice.setEnabled(false);
                         btnErampage.setEnabled(false);
                         btnEsuper.setEnabled(false);
                         btnRdark.setEnabled(false);
                         btnRsuper.setEnabled(false);
                         btnAsuper.setEnabled(false);
                         btnAfrenzy.setEnabled(false);
                    }
                }
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_btnAsuperMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanek;
    private javax.swing.JButton btnAcurar;
    private javax.swing.JButton btnAfrenzy;
    private javax.swing.JButton btnAice;
    private javax.swing.JButton btnAsuper;
    private javax.swing.JButton btnEcurar;
    private javax.swing.JButton btnEfiraga;
    private javax.swing.JButton btnErampage;
    private javax.swing.JButton btnEsuper;
    private javax.swing.JButton btnRESET;
    private javax.swing.JButton btnRcurar;
    private javax.swing.JButton btnRdark;
    private javax.swing.JButton btnRsuper;
    private javax.swing.JButton btnRthundaga;
    private javax.swing.JButton btnSALIR;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblActions;
    private javax.swing.JProgressBar vida1;
    private javax.swing.JProgressBar vida2;
    private javax.swing.JProgressBar vida3;
    private javax.swing.JProgressBar vida4;
    // End of variables declaration//GEN-END:variables
}
